application: valentvolta
version: 1
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /.*
  static_files: index.html
  upload: index.html
